# Generated by Django 4.0.4 on 2022-04-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='description_review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='title_review',
        ),
    ]
