# Generated by Django 4.0.4 on 2022-05-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_rename_description_review_description_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10),
        ),
    ]
