# Generated by Django 4.0.4 on 2022-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_ticket_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='note',
        ),
        migrations.AddField(
            model_name='review',
            name='note',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10),
        ),
    ]
