# Generated by Django 4.0.3 on 2022-03-31 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_subscribes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
